### PR TITLE
Fixes loaders not interacting with non-vanilla-sized cargo wagons

### PR DESCRIPTION
**Pull request by ReikaKalseki**
For more info, see [my issue](https://github.com/Yousei9/Loader-Redux/issues/18).

I have tested this code ingame, with both oddly-sized and vanilla wagons, and it works without issue.

### CODE REVIEW

**Comment by Yousei9** [comment]
Looks good to me.
Which mods add wagons that differ from vanilla width?

**Comment by ReikaKalseki** [comment]
I am working on one right now. The wagon is only one internally, not used as part of a train. Yes, it is a hack, but it is necessary so that I can have slot filters on it (chests do not support such filters).

**Comment by Yousei9** [comment]
I strongly suggest against using this "chest" with loader redux. The way I have to put items on belt lanes through script will utterly destroy performance.
For train interaction MiniLoader (disguised inserters) is a much better choice. I'm arguing if i shouldn't remove train interaction altogether.

**Comment by ReikaKalseki** [comment]
> The way I have to put items on belt lanes through script will utterly destroy performance.

Can you elaborate?

> For train interaction MiniLoader (disguised inserters) is a much better choice.

Hidden inserters - with a common example being Hacked Splitters - are very often claimed to cause extreme lag, so I doubt this.

> I'm arguing if i shouldn't remove train interaction altogether.

**Comment by Yousei9** [comment]
> Can you elaborate?

The internal code loaders use only connects to chests and crafting machines and seems to be really fast, perhaps has even less ups impact than inserter.
Cargo wagons however is a lua script extension done in ` local function wagon_transfer(wagon_data)`.  Putting items on both belt lanes every n ticks in lua is magnitudes less efficient than hidden inserters.

**Comment by ReikaKalseki** [comment]
> The main use of loaders is chest-belt connector.

For you, maybe. But most people - myself included - use them when throughput needs to be at a maximum and inserters cannot realistically keep up, and while it is rare for assemblers to be at those sort of speeds, trains *always* end up needing to dump thousands of items as fast as possible.

**Comment by Yousei9** [comment]
>For you, maybe. But most people - myself included - use them most when throughput needs to be at a maximum 

You should look at ups optimized builds for megabases instead of beginner bases.

> inserters cannot realistically keep up, and while it is rare for assemblers to be at those sort of speeds (you need like 8 stacked beacons full of speed modules, which most builds do NOT use to that degree), trains always end up needing to dump thousands of items as fast as possible.
Even on the slowest possible 180° vanilla rotation 6 stack inserters shuffle slightly more than 4 blue loaders worth of items between train and chest,


Using mods changing inserter angles like  bob inserters turns this heavily in favor of inserter. 2 Inserter can be made to shuffle 6 blue belts of items between chest and wagon.

**Comment by ReikaKalseki** [comment]
> You should look at ups optimized builds for megabases instead of beginner bases.

Few people make megabases, probably less than 1% of the playerbase. Megabase use cases are simply irrelevant to most people, and restricting functionality to only those use cases is akin to redesigning Firefox to load GitHub faster and more cleanly while outright breaking its ability to visit most of the rest of the internet.

> Even on the slowest possible 180° vanilla rotation 6 stack inserters shuffle slightly more than 4 blue loaders worth of items between train and chest,

In other words, even the best stack inserter - without changing the angle with mods - cannot compete with a loader. And the only solution to this is to use 90-degree inserters, which make the current bots-vs-belts debate look like nothing in comparison.

**Comment by Yousei9** [comment]
You are comparing apples and oranges.
For moving items between cargo wagon and chest Loaders only have downsides compared to vanilla stack inserters:
- cpu hungry script
- require 2.7 times more space (4x4 vs 6x1)
- can't be circuit controlled

**Comment by ReikaKalseki** [comment]
> I'd love to see the statistic basis for this statement.

I anticipated that and am currently conducting it now. Give me a day or two for results to be aggregated. It is a reddit post, not the most scientific of formats, but it is within my means, unlike ingame analytics.

That said, it should be fairly self-evident; a megabase is one hell of an achievement with a massive time requirement; most people do not have that kind of time, and it is rare in games - any game - for players to have that kind of accomplishment. Less than 5% of players complete puzzle games like Infinifactory or SpaceChem; Like 3% of the E:D playerbase has been to Saggitarius A-star; Few people build massive automated defence systems in Space Engineers or massive flying crafts in Beseige. And all of those are less demanding than a megabase is.

> Anyway I belong to the megabase group and all my mods are tailored to support this play style. If they are useful to other play styles that's great, but it will never be my focus.

Sure, but as I said above - having loader-train code in, if you never use loaders with trains, costs you nothing, but benefits a great many people. Removing it *gives* you nothing, and hurts many people. Why remove it?

> cpu hungry script

To a degree where it only matters in megabase setups - this disadvantage is nonexistent to most players.

> require 2.7 times more space (4x4 vs 6x1)

Inline space, maybe, but that is generally more expendable than "width space". This is of course build style dependent, but nonetheless real.

> can't be circuit controlled

Yes, they can, via their feed belts, which *can* be connected.

> Without buffer chests all your points are moot as your belts will run dry while trains move meaning you never needed fully compressed belts to begin with.

Where was the lack of buffer chests specified?

**Pull request merged**
